baseURL: "https://mahiuddin.me/"
languageCode: en-us
title: Md Mahiuddin | Backend Developer
theme: hugo-profile

Paginate: 6
disqusShortname: mahiuddin
googleAnalytics: G-KYDTVXC5V2

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    
    - identifier: catagory
      name: Catagory
      title: Catagory
      url: /tags
      weight: 1

    # # Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  author: Mahiuddin
  title: Mahiuddin
  description: I'm a backend developer. For backend development mostly work with Django framwork. I'm also very interested to work frontend. 
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # light

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   brandName: "Mahiuddin"
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Mahiuddin."
    subtitle: "I build things for the web"
    content: "A passionate Django web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
    image: /images/mahiuddin.png
    button:
      enable: true
      name: "Resume"
      url: "/md-mahiuddin.pdf"
      download: false 
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/mahiuddin-dev/
        - icon: fab fa-twitter
          url: https://twitter.com/mahiuddin_dev/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/mdmahiuddin/

      # customIcons:
      #   - icon: fab fa-linkedin
      #     url: https://linkedin.com/mdmahiuddin/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a software developer with a passion for web development. I have a background in Civil technology and learnig Computer Science through CS50, Open Source Society University. I have a strong interest in the intersection of technology. 
      I am currently working on a project that will be used to store managemengt.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Python"
        - "Django"
        - "REST API"
        - "Docker"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Developer"
        company: "Kernel Coder Lab"
        companyUrl: "#"
        date: "Jan 2023 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "#"
        content: "I am currently working as a software developer at Kernel Coder Lab in Rajshahi, Bangladesh."

      # - job: "Software Developer"
      #   company: "Amazon"
      #   companyUrl: "https://example.com"
      #   date: "Sep 2020 - Dec 2021"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   info:
      #     enable: true
      #     content: I worked as a software developer for more than one year in Amazon.
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Computer Science"
        school:
          name: "Open Source Society University"
        date: "2021 - present"
        content: |-
          Self-taught education. Ami to get a proper, well-rounded grounding in concepts fundamental to all computing disciplines.
      - title: "Diploma In Engineering"
        school:
          name: "Dinajpur Polytechnic Institute, Dinajpur"
          url: "https://www.dpi.edu.bd/"
        date: "2018 - 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |-
          I have completed my diploma degree in Civil technology.

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Problem Solving Certificate (HackerRank)
        content: I solved all problems with optimal solution.
        url: https://www.hackerrank.com/certificates/0bf378975d90
      - title: Python (Basic) Certificate (HackerRank)
        content: I solved all problems with optimal solution.
        url: https://www.hackerrank.com/certificates/c5cc2963a75f
      - title: URL Shorter
        content: Developed a URL Shorter and getting 1K+ short link per month.
        url: https://murlshort.herokuapp.com/
      - title: Google Digital Garage Certification
        content: Google marketing online course
        url: https://drive.google.com/file/d/1cEvfxHJlBOdlcc_AFzM2K1EtEzmOPgYa/view?usp=sharing

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Django CRUD Application 
        content: A CRUD web Application. This is a basic application. Where just anyone can add,edit or delete data. This is not authenticated.
        image: /images/projects/CRUD.png
        featured:
          name: Demo
          link: https://djangocrudapplication.herokuapp.com/
        badges:
          - "Djangp"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/mahiuddin-dev/CRUD-Application
        
      - title: URL Shorter
        content: A simple web app to short URL. Using Django for backend and bootstrap for frontend. Currently this application have 100+ user.
        image: /images/projects/url-shorter.png
        featured:
          name: Demo
          link: https://murlshort.herokuapp.com/
        badges:
          - "Djangp"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/mahiuddin-dev/Url-Shorter
        
      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/mahiuddin-dev/Image-Converter

  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: dev.mahiuddin@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/mahiuddin-dev/
      linkedin: https://www.linkedin.com/in/mdmahiuddin/
      twitter: https://twitter.com/mahiuddin-dev/
      facebook: https://facebook.com/mahiuddin.dev/

enableRobotsTXT: true
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
